
type User {
  _id: String!
  name: String!
  email: String!
  pwd: String!
  level: String!
}

type Todo {
  title: String!
  description: String!
  for: [String]!
  shouldBeIn: String!
  tagId: [String]!
}

type Tag {
  _id: ID!
  name: String!
  publishBy: String!
  description: String!
  color: String!
}

type Recipie {
  _id: ID!
  title: String!
  ingredients: String!
  steps: String!
  tagsId: String!
}

type Query {
  " users "
  getAllUsers: [User]
  getOneUserById(id: ID!): User
}