
type Users {
  _id: String!
  name: String!
  email: String!
  pwd: String!
  level: String!
}

type Todo {
  title: String
  description: String
  for: [String]
  shouldBeIn: String 
  tagId: [String]
}

type Query {
  " users "
  getAllUsers: [Users]
  getOneUserById(id: ID!): Users
}